In [1]:
import numpy as np # import numpy package


Syntax: numpy.array(object, dtype=None, copy=True, order=’K’, subok=False, ndmin=0)

In [2]:
one_d_array = np.array([1,2,3,4]) # create 1D array
print(one_d_array) # printing 1d array

[1 2 3 4]


To create 2D array, give items of lists in list to NumPy array() function.



In [3]:
two_d_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) # create 1D array
print(two_d_array) #printing 2D array


[[1 2 3]
 [4 5 6]
 [7 8 9]]


The type() function give the type of data.

Syntax: type(self, /, *args, **kwargs)

In [4]:
type(one_d_array) # give the type of data present in one_d_array variable

numpy.ndarray

The ndim attribute help to find the dimension of any NumPy array.

Syntax: array_name.ndim

In [6]:
one_d_array.ndim # find the dimension of one_d_array

1

The size attribute help to know, how many items present in a ndarray.

In [7]:
one_d_array.size

4

The shape attribute help to know the shape of NumPy ndarray. It gives output in the form of a tuple data type. Tuple represents the number of rows and columns. Ex: (rows, columns)

In [8]:
two_d_array.shape


(3, 3)

In [9]:
one_d_array.dtype

dtype('int32')

Ones metrics use NumPy ones() function.

Syntax: np.ones(shape, dtype=None, order=‘C’)

In [23]:
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

Zeros metrics use NumPy zeros() function.

Syntax: np.zeros(shape, dtype=None, order=‘C’)

In [11]:
np.zeros((3, 3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Empty metrics use NumPy empty() function.

Syntax: np.empty(shape, dtype=None, order=‘C’)

In [12]:
np.empty((2,4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 6.34380289e-321, 2.22809558e-312,
        2.14321575e-312]])

Create NumPy 1D array using arange() function

Syntax: np.arange([start,] stop[, step,], dtype=None)

In [13]:
arr = np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


Return evenly spaced numbers over a specified interval.

Syntax: np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0,)

In [18]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

Convert 1D array to multidimensional array using reshape() function

Syntax: np.reshape(a, newshape, order=‘C’)

In [19]:
arr_reshape = np.reshape(arr, (3,4))
print(arr_reshape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Convert multidimensional array in one dimensional

To convert multidimensional array into 1D use ravel() or flatten() function.

Syntax: np.ravel(array_name, order=‘C’)  or  array_name.ravel(order=‘C’)

               array_name.flatten(order=‘C’)

In [16]:
arr_reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

Transpose metrics

Syntax: np.transpose(array_name, axes=None)  or

                array_name.T

In [21]:
two_d_array.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])